import { Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, HardHat } from "lucide-react";
import { SectionHeading } from "@/components/bluechamp/SectionHeading";
import { slideLeft, slideRight } from "@/lib/animations";
import { subsidiaries } from "@/lib/constants";

export function AboutSection() {
  return <section className="bg-background py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-4 lg:grid-cols-2 lg:px-8"><motion.div variants={slideLeft} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }}><SectionHeading center={false} eyebrow="About Us" title="We Provide Effective Solutions" /><p className="text-lg leading-8 text-muted-foreground">Blue Champ Group of Companies was established in 2010 and is headquartered in Abu Dhabi, UAE. We provide skilled and unskilled manpower for local and international requirements, while managing employee affairs including medical insurance, sponsorship, government affairs and project deployment.</p><ul className="mt-8 grid gap-4">{subsidiaries.map((item) => <li key={item} className="flex items-center gap-3 font-semibold text-foreground"><CheckCircle2 className="h-5 w-5 text-accent" />{item}</li>)}</ul><Link to="/about" className="mt-8 inline-flex items-center gap-2 font-bold text-primary hover:text-accent">Learn More <ArrowRight className="h-4 w-4" /></Link></motion.div><motion.div variants={slideRight} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} className="relative min-h-[500px]"><div className="absolute left-10 top-0 grid h-64 w-64 rotate-45 place-items-center overflow-hidden rounded-2xl brand-gradient shadow-2xl"><HardHat className="h-28 w-28 -rotate-45 text-primary-foreground" /></div><div className="absolute right-8 top-28 grid h-72 w-72 rotate-45 place-items-center rounded-2xl bg-brand-navy shadow-2xl"><span className="-rotate-45 text-center font-heading text-3xl font-black text-primary-foreground">Engineering<br />Teams</span></div><div className="absolute bottom-0 left-24 grid h-56 w-56 rotate-45 place-items-center rounded-2xl bg-secondary shadow-xl"><span className="-rotate-45 text-center font-heading text-2xl font-black text-primary">Fit-Out<br />Works</span></div></motion.div></div></section>;
}
