import { motion } from "framer-motion";
import { Building2, Mail, MapPin, Phone, Send, Globe } from "lucide-react";
import { Button } from "@/components/ui/button";
import { contact, services } from "@/lib/constants";

export function ContactSection({ selectedService }: { selectedService?: string }) {
  const subject = selectedService ? `Quote request for ${selectedService}` : "";

  return <section id="quote-form" className="scroll-mt-24 bg-background py-24"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-2 lg:px-8"><motion.form initial={{ opacity: 0, x: -80 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.2 }} className="rounded-2xl border bg-card p-7 shadow-2xl"><h2 className="text-3xl font-black">Get a Quote</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input aria-label="Name" className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring" placeholder="Name" /><input aria-label="Company" className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring" placeholder="Company" /><input aria-label="Email" className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring" placeholder="Email" type="email" /><input aria-label="Phone" className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring" placeholder="Phone" /><select aria-label="Service Required" defaultValue={selectedService ?? ""} className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring sm:col-span-2"><option value="">Service Required</option>{services.map((s) => <option key={s.title} value={s.title}>{s.title}</option>)}</select><input aria-label="Subject" defaultValue={subject} className="rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring sm:col-span-2" placeholder="Subject" /><textarea aria-label="Message" defaultValue={selectedService ? `I would like to request a quote for ${selectedService}.` : ""} className="min-h-36 rounded-lg border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-ring sm:col-span-2" placeholder="Message" /></div><Button className="mt-6" variant="gradient" size="xl" type="button"><Send />Submit</Button></motion.form><motion.div initial={{ opacity: 0, x: 80 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.2 }} className="grid gap-5"><Info icon={MapPin} title="Location" text={contact.location} /><Info icon={Phone} title="Phone" text={contact.phones.join(" / ")} /><Info icon={Mail} title="Email" text={contact.emails.join(" / ")} /><Info icon={Globe} title="Website" text={contact.website} /><div className="grid min-h-56 place-items-center rounded-2xl border bg-secondary text-center"><Building2 className="mx-auto mb-3 h-12 w-12 text-primary" /><p className="font-bold">Map: Abu Dhabi, UAE</p></div></motion.div></div></section>;
}
function Info({ icon: Icon, title, text }: { icon: typeof MapPin; title: string; text: string }) { return <div className="flex gap-4 rounded-xl border bg-card p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-full bg-secondary text-primary"><Icon /></span><div><h3 className="font-black">{title}</h3><p className="text-muted-foreground">{text}</p></div></div>; }
